
package com.RealLis.specimenInhos.ws.wsdl.herenLisBarcode;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "interface_hr", targetNamespace = "http://tempurl.org", wsdlLocation = "http://172.16.0.100:6700/hyyy_wsbarcode/interface_hr.asmx?WSDL")
public class InterfaceHr
    extends Service
{

    private final static URL INTERFACEHR_WSDL_LOCATION;
    private final static WebServiceException INTERFACEHR_EXCEPTION;
    private final static QName INTERFACEHR_QNAME = new QName("http://tempurl.org", "interface_hr");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.0.100:6700/hyyy_wsbarcode/interface_hr.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTERFACEHR_WSDL_LOCATION = url;
        INTERFACEHR_EXCEPTION = e;
    }

    public InterfaceHr() {
        super(__getWsdlLocation(), INTERFACEHR_QNAME);
    }

    public InterfaceHr(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTERFACEHR_QNAME, features);
    }

    public InterfaceHr(URL wsdlLocation) {
        super(wsdlLocation, INTERFACEHR_QNAME);
    }

    public InterfaceHr(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTERFACEHR_QNAME, features);
    }

    public InterfaceHr(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterfaceHr(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InterfaceHrSoap
     */
    @WebEndpoint(name = "interface_hrSoap")
    public InterfaceHrSoap getInterfaceHrSoap() {
        return super.getPort(new QName("http://tempurl.org", "interface_hrSoap"), InterfaceHrSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfaceHrSoap
     */
    @WebEndpoint(name = "interface_hrSoap")
    public InterfaceHrSoap getInterfaceHrSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempurl.org", "interface_hrSoap"), InterfaceHrSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns InterfaceHrSoap
     */
    @WebEndpoint(name = "interface_hrSoap12")
    public InterfaceHrSoap getInterfaceHrSoap12() {
        return super.getPort(new QName("http://tempurl.org", "interface_hrSoap12"), InterfaceHrSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfaceHrSoap
     */
    @WebEndpoint(name = "interface_hrSoap12")
    public InterfaceHrSoap getInterfaceHrSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempurl.org", "interface_hrSoap12"), InterfaceHrSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTERFACEHR_EXCEPTION!= null) {
            throw INTERFACEHR_EXCEPTION;
        }
        return INTERFACEHR_WSDL_LOCATION;
    }

}
