
package com.RealLis.specimenInhos.ws.wsdl.herenLisBarcode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "interface_hrSoap", targetNamespace = "http://tempurl.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InterfaceHrSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "uf_about", action = "http://tempurl.org/uf_about")
    @WebResult(name = "uf_aboutResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "uf_about", targetNamespace = "http://tempurl.org", className = "com.RealLis.specimenInhos.ws.wsdl.herenLisBarcode.UfAbout")
    @ResponseWrapper(localName = "uf_aboutResponse", targetNamespace = "http://tempurl.org", className = "com.RealLis.specimenInhos.ws.wsdl.herenLisBarcode.UfAboutResponse")
    public String ufAbout();

    /**
     * 
     * @param asBarcode
     * @param asCzz
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "uf_pack", action = "http://tempurl.org/uf_pack")
    @WebResult(name = "uf_packResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "uf_pack", targetNamespace = "http://tempurl.org", className = "com.RealLis.specimenInhos.ws.wsdl.herenLisBarcode.UfPack")
    @ResponseWrapper(localName = "uf_packResponse", targetNamespace = "http://tempurl.org", className = "com.RealLis.specimenInhos.ws.wsdl.herenLisBarcode.UfPackResponse")
    public String ufPack(
        @WebParam(name = "as_czz", targetNamespace = "http://tempurl.org")
        String asCzz,
        @WebParam(name = "as_barcode", targetNamespace = "http://tempurl.org")
        String asBarcode);

    /**
     * 
     * @param asCzz
     * @param asWlbh
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "uf_trans", action = "http://tempurl.org/uf_trans")
    @WebResult(name = "uf_transResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "uf_trans", targetNamespace = "http://tempurl.org", className = "com.RealLis.specimenInhos.ws.wsdl.herenLisBarcode.UfTrans")
    @ResponseWrapper(localName = "uf_transResponse", targetNamespace = "http://tempurl.org", className = "com.RealLis.specimenInhos.ws.wsdl.herenLisBarcode.UfTransResponse")
    public String ufTrans(
        @WebParam(name = "as_czz", targetNamespace = "http://tempurl.org")
        String asCzz,
        @WebParam(name = "as_wlbh", targetNamespace = "http://tempurl.org")
        String asWlbh);

    /**
     * 
     * @param asJosn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "uf_josn", action = "http://tempurl.org/uf_josn")
    @WebResult(name = "uf_josnResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "uf_josn", targetNamespace = "http://tempurl.org", className = "com.RealLis.specimenInhos.ws.wsdl.herenLisBarcode.UfJosn")
    @ResponseWrapper(localName = "uf_josnResponse", targetNamespace = "http://tempurl.org", className = "com.RealLis.specimenInhos.ws.wsdl.herenLisBarcode.UfJosnResponse")
    public String ufJosn(
        @WebParam(name = "as_josn", targetNamespace = "http://tempurl.org")
        String asJosn);

}
