
package com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceLisSoap", targetNamespace = "http://172.16.1.36")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceLisSoap {


    /**
     * HelloWorld可用于测试服务是否正常。
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://172.16.1.36/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.HelloWorldResponse")
    public String helloWorld();

    /**
     * zhLisHeren，HIS与LIS通过HL7协议进行交易的主要方法
     * 
     * @param strMessage
     * @param strDataType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://172.16.1.36/zhLisHeren")
    @WebResult(name = "zhLisHerenResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "zhLisHeren", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.ZhLisHeren")
    @ResponseWrapper(localName = "zhLisHerenResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.ZhLisHerenResponse")
    public String zhLisHeren(
        @WebParam(name = "strMessage", targetNamespace = "http://172.16.1.36")
        String strMessage,
        @WebParam(name = "strDataType", targetNamespace = "http://172.16.1.36")
        String strDataType);

    /**
     * LabBarMake，生成条形码方法，入参为病历号：[PatientID]
     * 
     * @param strPatientID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabBarMake", action = "http://172.16.1.36/LabBarMake")
    @WebResult(name = "LabBarMakeResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabBarMake", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabBarMake")
    @ResponseWrapper(localName = "LabBarMakeResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabBarMakeResponse")
    public String labBarMake(
        @WebParam(name = "strPatientID", targetNamespace = "http://172.16.1.36")
        String strPatientID);

    /**
     * LabDownInfoAll，从HIS中下载信息总方法，支持的参数为：科室信息，职工信息，检验项目，收费项目。
     * 
     * @param strDownOrder
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoAll", action = "http://172.16.1.36/LabDownInfoAll")
    @WebResult(name = "LabDownInfoAllResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabDownInfoAll", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoAll")
    @ResponseWrapper(localName = "LabDownInfoAllResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoAllResponse")
    public String labDownInfoAll(
        @WebParam(name = "strDownOrder", targetNamespace = "http://172.16.1.36")
        String strDownOrder);

    /**
     * LabDownInfoDept，从HIS中下载科室信息,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoDept", action = "http://172.16.1.36/LabDownInfoDept")
    @WebResult(name = "LabDownInfoDeptResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabDownInfoDept", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoDept")
    @ResponseWrapper(localName = "LabDownInfoDeptResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoDeptResponse")
    public String labDownInfoDept();

    /**
     * LabDownInfoStaff，从HIS中下载职工信息,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoStaff", action = "http://172.16.1.36/LabDownInfoStaff")
    @WebResult(name = "LabDownInfoStaffResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabDownInfoStaff", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoStaff")
    @ResponseWrapper(localName = "LabDownInfoStaffResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoStaffResponse")
    public String labDownInfoStaff();

    /**
     * LabDownInfoItem，从HIS中下载检验项目,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoItem", action = "http://172.16.1.36/LabDownInfoItem")
    @WebResult(name = "LabDownInfoItemResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabDownInfoItem", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoItem")
    @ResponseWrapper(localName = "LabDownInfoItemResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoItemResponse")
    public String labDownInfoItem();

    /**
     * LabDownInfoFee，从HIS中下载收费项目,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoFee", action = "http://172.16.1.36/LabDownInfoFee")
    @WebResult(name = "LabDownInfoFeeResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabDownInfoFee", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoFee")
    @ResponseWrapper(localName = "LabDownInfoFeeResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoFeeResponse")
    public String labDownInfoFee();

    /**
     *  WebTest用于开发人员测试，参数传入时
     * 
     * @param strmess
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WebTest", action = "http://172.16.1.36/WebTest")
    @WebResult(name = "WebTestResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "WebTest", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.WebTest")
    @ResponseWrapper(localName = "WebTestResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.WebTestResponse")
    public String webTest(
        @WebParam(name = "strmess", targetNamespace = "http://172.16.1.36")
        String strmess);

}
