
package com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceLisSoap", targetNamespace = "http://172.16.1.36")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceLisSoap {


    /**
     * ----可用于测试服务是否正常。
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://172.16.1.36/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.HelloWorldResponse")
    public String helloWorld();

    /**
     * ----HIS与LIS进行交易的主要方法, strMessage消息主体，strDataType消息类型：HL7, JSON, XML 。
     * 
     * @param strMessage
     * @param strDataType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://172.16.1.36/zhLisHeren")
    @WebResult(name = "zhLisHerenResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "zhLisHeren", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.ZhLisHeren")
    @ResponseWrapper(localName = "zhLisHerenResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.ZhLisHerenResponse")
    public String zhLisHeren(
        @WebParam(name = "strMessage", targetNamespace = "http://172.16.1.36")
        String strMessage,
        @WebParam(name = "strDataType", targetNamespace = "http://172.16.1.36")
        String strDataType);

    /**
     * ----生成条形码方法，入参strPatientID为病历号：[VISIT_NUMBER]
     * 
     * @param strPatientID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabBarMake", action = "http://172.16.1.36/LabBarMake")
    @WebResult(name = "LabBarMakeResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabBarMake", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabBarMake")
    @ResponseWrapper(localName = "LabBarMakeResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabBarMakeResponse")
    public String labBarMake(
        @WebParam(name = "strPatientID", targetNamespace = "http://172.16.1.36")
        String strPatientID);

    /**
     * ----从HIS中下载信息总方法，支持的参数为：科室信息，职工信息，检验项目，收费项目。
     * 
     * @param strDownOrder
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoAll", action = "http://172.16.1.36/LabDownInfoAll")
    @WebResult(name = "LabDownInfoAllResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabDownInfoAll", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoAll")
    @ResponseWrapper(localName = "LabDownInfoAllResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoAllResponse")
    public String labDownInfoAll(
        @WebParam(name = "strDownOrder", targetNamespace = "http://172.16.1.36")
        String strDownOrder);

    /**
     * ----从HIS中下载【 科室信息 】,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoDept", action = "http://172.16.1.36/LabDownInfoDept")
    @WebResult(name = "LabDownInfoDeptResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabDownInfoDept", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoDept")
    @ResponseWrapper(localName = "LabDownInfoDeptResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoDeptResponse")
    public String labDownInfoDept();

    /**
     * ----从HIS中下载【职工信息】,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoStaff", action = "http://172.16.1.36/LabDownInfoStaff")
    @WebResult(name = "LabDownInfoStaffResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabDownInfoStaff", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoStaff")
    @ResponseWrapper(localName = "LabDownInfoStaffResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoStaffResponse")
    public String labDownInfoStaff();

    /**
     * ----从HIS中下载【套餐项目】,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoItem", action = "http://172.16.1.36/LabDownInfoItem")
    @WebResult(name = "LabDownInfoItemResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabDownInfoItem", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoItem")
    @ResponseWrapper(localName = "LabDownInfoItemResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoItemResponse")
    public String labDownInfoItem();

    /**
     * ----从HIS中下载【收费项目】,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoFee", action = "http://172.16.1.36/LabDownInfoFee")
    @WebResult(name = "LabDownInfoFeeResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabDownInfoFee", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoFee")
    @ResponseWrapper(localName = "LabDownInfoFeeResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabDownInfoFeeResponse")
    public String labDownInfoFee();

    /**
     * ----向平台发送条形码状态，strBarCode要求条码全码
     *          0=申请中(可退费)；1=已申请；2=条码已打印；3=标本已采集；5=标本已核收；
     *          6=已执行（上机）；D= 取消中；P初步报告；F=确认报告，11=LIS退回标本；H=标本已送出；Y=送达
     * 
     * @param strBarCode
     * @param strOrderStatus
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetBarOrderStatus", action = "http://172.16.1.36/SetBarOrderStatus")
    @WebResult(name = "SetBarOrderStatusResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "SetBarOrderStatus", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.SetBarOrderStatus")
    @ResponseWrapper(localName = "SetBarOrderStatusResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.SetBarOrderStatusResponse")
    public String setBarOrderStatus(
        @WebParam(name = "strBarCode", targetNamespace = "http://172.16.1.36")
        String strBarCode,
        @WebParam(name = "strOrderStatus", targetNamespace = "http://172.16.1.36")
        String strOrderStatus);

    /**
     * ----向平台发送收费交易！ strBarCode要求全码， intChargeStatus：1收费，-1退费
     * 
     * @param strBarCode
     * @param intChargeStatus
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabChargeFee", action = "http://172.16.1.36/LabChargeFee")
    @WebResult(name = "LabChargeFeeResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "LabChargeFee", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabChargeFee")
    @ResponseWrapper(localName = "LabChargeFeeResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.LabChargeFeeResponse")
    public String labChargeFee(
        @WebParam(name = "strBarCode", targetNamespace = "http://172.16.1.36")
        String strBarCode,
        @WebParam(name = "intChargeStatus", targetNamespace = "http://172.16.1.36")
        int intChargeStatus);

    /**
     * ----向平台发送危急值交易 ！strSeqNo对应L_TSXX.SEQNO
     * 
     * @param strSeqNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendRiskValue", action = "http://172.16.1.36/SendRiskValue")
    @WebResult(name = "SendRiskValueResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "SendRiskValue", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.SendRiskValue")
    @ResponseWrapper(localName = "SendRiskValueResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.SendRiskValueResponse")
    public String sendRiskValue(
        @WebParam(name = "strSeqNo", targetNamespace = "http://172.16.1.36")
        String strSeqNo);

    /**
     * ----取LIS排队叫号！参数strPatientId，病人标识号
     * 
     * @param strPatientId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetQueueNo", action = "http://172.16.1.36/GetQueueNo")
    @WebResult(name = "GetQueueNoResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "GetQueueNo", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.GetQueueNo")
    @ResponseWrapper(localName = "GetQueueNoResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.GetQueueNoResponse")
    public String getQueueNo(
        @WebParam(name = "strPatientId", targetNamespace = "http://172.16.1.36")
        String strPatientId);

    /**
     * ----用于向和仁直接转发消息，strMessage 消息内容，strDataType数据类型，JSON,HL7,XML
     * 
     * @param strMessage
     * @param strDataType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TransferHeren", action = "http://172.16.1.36/TransferHeren")
    @WebResult(name = "TransferHerenResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "TransferHeren", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.TransferHeren")
    @ResponseWrapper(localName = "TransferHerenResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.TransferHerenResponse")
    public String transferHeren(
        @WebParam(name = "strMessage", targetNamespace = "http://172.16.1.36")
        String strMessage,
        @WebParam(name = "strDataType", targetNamespace = "http://172.16.1.36")
        String strDataType);

    /**
     * ----用于开发人员测试，参数传入时
     * 
     * @param strmess
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WebTest", action = "http://172.16.1.36/WebTest")
    @WebResult(name = "WebTestResult", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "WebTest", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.WebTest")
    @ResponseWrapper(localName = "WebTestResponse", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.WebTestResponse")
    public String webTest(
        @WebParam(name = "strmess", targetNamespace = "http://172.16.1.36")
        String strmess);

    /**
     * ----核酸结果查询，JSON
     * 
     * @param strJson
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryCov19", action = "http://172.16.1.36/QueryCov19")
    @WebResult(name = "QueryCov19Result", targetNamespace = "http://172.16.1.36")
    @RequestWrapper(localName = "QueryCov19", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.QueryCov19")
    @ResponseWrapper(localName = "QueryCov19Response", targetNamespace = "http://172.16.1.36", className = "com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet.QueryCov19Response")
    public String queryCov19(
        @WebParam(name = "strJson", targetNamespace = "http://172.16.1.36")
        String strJson);

}
