
package com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "WebServiceLisHttpGet", targetNamespace = "http://172.16.1.36")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceLisHttpGet {


    /**
     * HelloWorld�����ڲ��Է����Ƿ�������
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String helloWorld();

    /**
     * zhLisHeren��HIS��LISͨ��HL7Э����н��׵���Ҫ����
     *
     * @param strMessage
     * @param strDataType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String zhLisHeren(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strMessage")
                    String strMessage,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strDataType")
                    String strDataType);

    /**
     * LabBarMake�����������뷽�������Ϊ�����ţ�[PatientID]
     *
     * @param strPatientID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabBarMake")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String labBarMake(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strPatientID")
                    String strPatientID);

    /**
     * LabDownInfoAll����HIS��������Ϣ�ܷ�����֧�ֵĲ���Ϊ��������Ϣ��ְ����Ϣ��������Ŀ���շ���Ŀ��
     *
     * @param strDownOrder
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoAll")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String labDownInfoAll(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strDownOrder")
                    String strDownOrder);

    /**
     * LabDownInfoDept����HIS�����ؿ�����Ϣ,�޲�����
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoDept")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String labDownInfoDept();

    /**
     * LabDownInfoStaff����HIS������ְ����Ϣ,�޲�����
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoStaff")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String labDownInfoStaff();

    /**
     * LabDownInfoItem����HIS�����ؼ�����Ŀ,�޲�����
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoItem")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String labDownInfoItem();

    /**
     * LabDownInfoFee����HIS�������շ���Ŀ,�޲�����
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoFee")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String labDownInfoFee();

    /**
     * SetBarOrderStatus����ƽ̨����������״̬��strBarCodeҪ��ȫ��
     *          0=������(���˷�)��1=�����룻2=�����Ѵ�ӡ��3=�걾�Ѳɼ���5=�걾�Ѻ��գ�6=��ִ�У�P�������棻F=ȷ�ϱ��棬11=LIS�˻ر걾��H=�걾���ͳ���Y=�ʹ�
     *
     * @param strBarCode
     * @param strOrderStatus
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetBarOrderStatus")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String setBarOrderStatus(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strBarCode")
                    String strBarCode,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strOrderStatus")
                    String strOrderStatus);

    /**
     * LabChargeFee����ƽ̨�����շѽ��ף� strBarCodeҪ��ȫ�룬 intChargeStatus��1�շѣ�-1�˷�
     *
     * @param strBarCode
     * @param intChargeStatus
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabChargeFee")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String labChargeFee(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strBarCode")
                    String strBarCode,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "intChargeStatus")
                    String intChargeStatus);

    /**
     * SendRiskValue����ƽ̨�����շѽ��ף�
     *
     * @param strSampleNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendRiskValue")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String sendRiskValue(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strSampleNo")
                    String strSampleNo);

    /**
     * GetQueueNo��ȡLIS�Ŷӽкţ�
     *
     * @param strPatientId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetQueueNo")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String getQueueNo(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strPatientId")
                    String strPatientId);

    /**
     *  WebTest���ڿ�����Ա���ԣ���������ʱ
     *
     * @param strmess
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WebTest")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    String webTest(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strmess")
                    String strmess);

}
