
package com.RealLis.specimenInhos.ws.wsdl.zhlisWsHerenLet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceLisHttpPost", targetNamespace = "http://172.16.1.36")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceLisHttpPost {


    /**
     * HelloWorld可用于测试服务是否正常。
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    public String helloWorld();

    /**
     * zhLisHeren，HIS与LIS通过HL7协议进行交易的主要方法
     * 
     * @param strMessage
     * @param strDataType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    public String zhLisHeren(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strMessage")
        String strMessage,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strDataType")
        String strDataType);

    /**
     * LabBarMake，生成条形码方法，入参为病历号：[PatientID]
     * 
     * @param strPatientID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabBarMake")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    public String labBarMake(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strPatientID")
        String strPatientID);

    /**
     * LabDownInfoAll，从HIS中下载信息总方法，支持的参数为：科室信息，职工信息，检验项目，收费项目。
     * 
     * @param strDownOrder
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoAll")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    public String labDownInfoAll(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strDownOrder")
        String strDownOrder);

    /**
     * LabDownInfoDept，从HIS中下载科室信息,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoDept")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    public String labDownInfoDept();

    /**
     * LabDownInfoStaff，从HIS中下载职工信息,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoStaff")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    public String labDownInfoStaff();

    /**
     * LabDownInfoItem，从HIS中下载检验项目,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoItem")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    public String labDownInfoItem();

    /**
     * LabDownInfoFee，从HIS中下载收费项目,无参数！
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LabDownInfoFee")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    public String labDownInfoFee();

    /**
     *  WebTest用于开发人员测试，参数传入时
     * 
     * @param strmess
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WebTest")
    @WebResult(name = "string", targetNamespace = "http://172.16.1.36", partName = "Body")
    public String webTest(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strmess")
        String strmess);

}
