
package com.RealLis.specimenInhos.ws.wsdl.LisCommonWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LisCommonWS", targetNamespace = "http://tempuri.org", wsdlLocation = "http://172.16.18.50:57772/csp/healthshare/taiyi/services/HEREN.SysProdu.LIS.BS.LisCommonWS.CLS?WSDL=1")
public class LisCommonWS
    extends Service
{

    private final static URL LISCOMMONWS_WSDL_LOCATION;
    private final static WebServiceException LISCOMMONWS_EXCEPTION;
    private final static QName LISCOMMONWS_QNAME = new QName("http://tempuri.org", "LisCommonWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.18.50:57772/csp/healthshare/taiyi/services/HEREN.SysProdu.LIS.BS.LisCommonWS.CLS?WSDL=1");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISCOMMONWS_WSDL_LOCATION = url;
        LISCOMMONWS_EXCEPTION = e;
    }

    public LisCommonWS() {
        super(__getWsdlLocation(), LISCOMMONWS_QNAME);
    }

    public LisCommonWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISCOMMONWS_QNAME, features);
    }

    public LisCommonWS(URL wsdlLocation) {
        super(wsdlLocation, LISCOMMONWS_QNAME);
    }

    public LisCommonWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISCOMMONWS_QNAME, features);
    }

    public LisCommonWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LisCommonWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LisCommonWSSoap
     */
    @WebEndpoint(name = "LisCommonWSSoap")
    public LisCommonWSSoap getLisCommonWSSoap() {
        return super.getPort(new QName("http://tempuri.org", "LisCommonWSSoap"), LisCommonWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LisCommonWSSoap
     */
    @WebEndpoint(name = "LisCommonWSSoap")
    public LisCommonWSSoap getLisCommonWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org", "LisCommonWSSoap"), LisCommonWSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISCOMMONWS_EXCEPTION!= null) {
            throw LISCOMMONWS_EXCEPTION;
        }
        return LISCOMMONWS_WSDL_LOCATION;
    }

}
